import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Hero from "./components/Hero";
import About from "./components/About";
import Experience from "./components/WorkExperience";
import Skills from "./components/skills";
import Projects  from "./components/Projects";
import Contact  from "./components/contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Luyolo pondo portfolio",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory 
    overflow-scroll z-0">
    
    <Header/>

   {/*--Hero--*/}
    <section id="Hero" className="snap-start">
      <Hero/>
    </section>


    {/*--About--*/}
     <section id="about" className="snap-center">
      <About/>
     </section>


      {/*--Experience--*/}
       <section id="experience" className="snap-center" >
         <Experience/>
       </section>

      {/*--Skills--*/}
       <section id="skill" className="snap-start" >
         <Skills/>
       </section>


     {/*--Projects--*/}
      <section id="projects" className="snap-start" >
         <Projects/>
       </section>
   
    {/*--Contact Me--*/}
    <section id="projects" className="snap-start" >
         <Contact/>
       </section>
      

    
 </div>

  );
}
